export const PENGUINS = [
    {
        "no": 1,
        "name": "エンペラーペンギン",
        "types": "エンペラーペンギン属",
        "eTypes": "Aptenodytes",
        "img": "Emperor",
        "disabled": false,
        "ibodyLength": "100～130cm",
        "explanation": "最大のペンギンで、冬の南極大陸で過酷な寒さを耐え、繁殖を行う唯一の種。一回り小さく、体色はより鮮やかなキングペンギンと混同されることもあるが、繁殖行動や生息地、分布が大きく異なる。通常は海氷上で繁殖し、陸地の上で繁殖するコロニーは3つしか確認されていない。つまりエンペラーペンギンの多くは、大地に足をつけることなく一生を過ごす。鳥類のなかでも極めて珍しい特徴だ。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 2,
        "name": "キングペンギン",
        "types": "エンペラーペンギン属",
        "eTypes": "Aptenodytes",
        "img": "King",
        "disabled": false,
        "ibodyLength": "85～95cm",
        "explanation": "ペンギン全種のうち2番目に大きく、最も色鮮やかな種。より大型で色の薄いエンペラーペンギンと混同されやすいが、繁殖行動や生息地、分布が大きく異なる。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 3,
        "name": "アデリーペンギン",
        "types": "アデリーペンギン属",
        "eTypes": "Pygoscelis",
        "img": "Adelie",
        "disabled": false,
        "ibodyLength": "70～73cm",
        "explanation": "ペンギン全種のうち最も南方に生息し、短い夏の間に、南緯77度33分までの範囲で繁殖する。縄張意識が強く、怒りっぽく攻撃的。ロス海域に残る半化石化したアデリーペンギンの遺骨の年代は、他のどの種よりも古く、4万5000年前にまで遡る。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 4,
        "name": "ジェンツーペンギン",
        "types": "アデリーペンギン属",
        "eTypes": "Pygoscelis",
        "img": "Gentoo",
        "disabled": false,
        "ibodyLength": "75～90cm",
        "explanation": "ペンギン全種のうち3番目に大きい。独特の外見のため、他の種との混同はない。最も泳ぎの速い鳥とされ、最高時速36kmが記録されている。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 5,
        "name": "ヒゲペンギン",
        "types": "アデリーペンギン属",
        "eTypes": "Pygoscelis",
        "img": "Chinstrap",
        "disabled": false,
        "ibodyLength": "68～76cm",
        "explanation": "常に敏捷で、大胆かつ攻撃的。波に浸食されて孤立した氷山の上で観察されることが多い。顔に独特の模様があるため、他の種と混同されることはない。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 6,
        "name": "ガラパゴスペンギン",
        "types": "フンボルトペンギン属",
        "eTypes": "Spheniscus",
        "img": "Galapagos",
        "disabled": false,
        "ibodyLength": "48～53cm",
        "explanation": "体に帯模様のある4種のうち最も小さく、最も北部に生息する種。熱帯気候だが周囲の海水温が低い地域で繁殖する。フンボルトペンギンと最も近縁。体が小さく、分布が完全に孤立しているため、他の種と混同されることはない。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 7,
        "name": "ケープペンギン",
        "types": "フンボルトペンギン属",
        "eTypes": "Spheniscus",
        "img": "Cape",
        "disabled": false,
        "ibodyLength": "60～70cm",
        "explanation": "中くらいの大きさ。温暖な地域で生息する。アフリカ大陸で繁殖する唯一の種。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 8,
        "name": "フンボルトペンギン",
        "types": "フンボルトペンギン属",
        "eTypes": "Spheniscus",
        "img": "Humboldt",
        "disabled": false,
        "ibodyLength": "65～70cm",
        "explanation": "中くらいの大きさで温暖な地域に生息する種。外見が似ていて分布が一部重なるマゼランペンギンと混同されることもあるが、黒い帯が2本ではなく1本だけなので、陸上では容易に判別できる。動物園で見られるペンギンのほとんどがこの種である。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 9,
        "name": "マゼランペンギン",
        "types": "フンボルトペンギン属",
        "eTypes": "Spheniscus",
        "img": "Magellanic",
        "disabled": false,
        "ibodyLength": "70cm",
        "explanation": "温暖な地に暮らす、体に帯模様のある種では最大のペンギン。とても喧嘩っ早く、攻撃的。外見が似ていて分布が一部重なるフンボルトペンギンと混同されることもある。胸の黒い帯が1本ではなく2本あるので、陸上ではすぐ判別できる。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 10,
        "name": "フィヨルドランドペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Fiordland",
        "disabled": false,
        "ibodyLength": "55～60cm",
        "explanation": "ユーディプテス属の中で最も臆病で、ニュージーランドに生息するペンギンの中で最も希少な種。とくに水に濡れている状態や海上では、冠羽のある他の種と混同しやすい。とりわけスネアーズペンギンやシュレーターペンギンは、大きさや立ち姿が似ており、分布も隣接しているため混同しやすい。くちばしの根元を囲む裸出したピンク色の皮膚がないのが特徴。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 11,
        "name": "シュレーターペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Erect-crested",
        "disabled": false,
        "ibodyLength": "60～67cm",
        "explanation": "詳しいことが分かっていない種の1つ。とくに水に濡れている状態や海上では、冠羽のある他の種、とりわけフィヨルドランドペンギンやスネアーズペンギンと混同されやすいが、丸く膨らんだ頭頂部や、くちばしが細長くて根元のピンクの皮膚が目立たないこと、喉まわりが太いこと、などの違いがある。また他の種と異なり、ピンと立ち上がった冠羽を(乾いていれば)自由に上げ下げできる。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 12,
        "name": "スネアーズペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Snares",
        "disabled": false,
        "ibodyLength": "51～61cm",
        "explanation": "ユーディプテス属の他の種ほど攻撃的ではない。とくに水に濡れている状態や海上では、同属の他の種、とりわけフィヨルドランドペンギンやシュレーターペンギンと混同しやすい。しばしば木の幹や枝に止まっていて、地上から2メートルも高いところにいることもある。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 13,
        "name": "マカロニペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Macaroni",
        "disabled": false,
        "ibodyLength": "71cm",
        "explanation": "全種のうち最も生息数の多いペンギン。また冠羽のある7種のうち、最も南部に分布している。近縁種のロイヤルペンギンとは、顔の色が黒(マカロニ)と白(ロイヤル)で正反対のため、ほぼ混同することはないが、喉が灰色の幼鳥の段階では違いが分かりにくい。海上では、他の冠羽のある種と識別することは難しいかもしれない。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 14,
        "name": "ロイヤルペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Royal",
        "disabled": false,
        "ibodyLength": "65～75cm",
        "explanation": "マカロニペンギンと非常に近縁の種ではあるが、マカロニペンギンの成鳥は顔が黒く、混同することはない。幼鳥は両種とも灰色がかった喉だが、ロイヤルペンギンの方が淡い色をしていることが多い。冠羽が完全に生えていない若鳥は、とりわけ海上では他の種と混同されやすい。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 15,
        "name": "キタイワトビペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Northern-Rockhopper",
        "disabled": false,
        "ibodyLength": "55～65cm",
        "explanation": "ミナミイワトビペンギンに似ているが、一回り大きく、翼やくちばしが長めで、翼の内側の黒い部分が多く、冠羽もより鮮やかな黄色をしている。また繁殖期も早く、育雛期間も短い。繁殖地である火山群島には沿岸の大陸棚がないため、同属の種では唯一、繁殖期は外洋で採餌を行う。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 16,
        "name": "ミナミイワトビペンギン",
        "types": "マカロニペンギン属",
        "eTypes": "Eudyptes",
        "img": "Southern-Rockhopper",
        "disabled": false,
        "ibodyLength": "45～58cm",
        "explanation": "群れを作る習性が非常に強く、攻撃的で、繁殖も換羽も密集して行う。キタイワトビペンギンに似ているが、一回り小さく、翼やくちばしが短めで、翼の内側の黒い部分が薄く、冠羽も落ち着いた黄色をしている。とくに幼鳥の頃や海の上では、冠羽のある他の種と混同されやすい。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 17,
        "name": "キガシラペンギン",
        "types": "キガシラペンギン属",
        "eTypes": "Megadyptes",
        "img": "Yellow-eyed",
        "disabled": false,
        "ibodyLength": "56～78cm",
        "explanation": "メガディプテス属で現存する唯一の種で、ペンギン全種のなかでも特に希少な、絶滅の危機にある種の1つ。また最も社会性が弱く、とても臆病。独特の外見から、他の種と混同する ことはない。絶滅したワイタハペンギン (Megadyptes waitaha)と近縁。キガシラペンギンより小型のワイタハペンギンの存在は、1000年前の骨を近年 DNA解析した結果、発見されたばかり。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    },
    {
        "no": 18,
        "name": "コガタペンギン",
        "types": "コガタペンギン属",
        "eTypes": "Eudyptula",
        "img": "Littleblue",
        "disabled": false,
        "ibodyLength": "40～45cm",
        "explanation": "ペンギン全種のなかで最も小さい種。陸上では夜行性で、夜になると小さな群れで海から巣穴に帰り、夜明け前に採餌に出かける。人間のいない地域では、日中に浜辺で休むことも ある。亜種の分布域はほとんど重ならない。",
        "isMegaEvolution": false,
        "evolutions": [2],
        "abilities": ["しんりょく"],
        "hiddenAbilities": ["ようりょくそ"],
        "stats": {
          "hp": 45,
          "attack": 49,
          "defence": 49,
          "spAttack": 65,
          "spDefence": 65,
          "speed": 45
        }
    }
  ]